#!/usr/bin/env bash
# gen-llms-full.sh — regenerate llms-full.txt: every markdown file referenced
# in llms.txt, concatenated in listed order with a path header per file.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
OUT="$REPO_DIR/llms-full.txt"
BASE='https://raw.githubusercontent.com/ArangoGutierrez/claude-toolkit/main/'
{
  echo "# claude-toolkit — full docs corpus (generated by scripts/gen-llms-full.sh)"
  echo
  grep -oE "\($BASE[^)]+\.md\)" "$REPO_DIR/llms.txt" | sed -e "s|($BASE||" -e 's|)$||' | \
  while IFS= read -r rel; do
    [ -f "$REPO_DIR/$rel" ] || { echo "MISSING: $rel" >&2; exit 1; }
    printf '\n===== %s =====\n\n' "$rel"
    cat "$REPO_DIR/$rel"
  done
} > "$OUT"
echo "wrote $OUT ($(wc -l < "$OUT") lines)"
